### ISSUE TITLE
check that user is available

### ISSUE THREAD

**Issue by gandesc** [laravel-enso/TrackWho#5]
If you make changes to a model from CLI, such as when running migrations with some logic, the trait will attempt to fill in user data, and it's unavailable.

We should check that the app/auth/user data is available before trying to use it.

Might be able to use `App::runningInConsole()`

**Comment by aocneanu** [comment]
good point.

**Comment by aocneanu** [comment]
when running in console we should `auth->onceUsingId(xx)` before creating / updating / deleting the model
